### ISSUE TITLE
Activity Log

### ISSUE THREAD

**Issue by karolsojko** [x-team/the-vault#19]
Would be nice to have an activity log stored, so we could see information like this:
- User X gave User Y 1 coin
- User Y spent 3 coins
...

**Comment by keremgocen** [comment]
@karolsojko can I kidnap an IAM profile over x-team aws account to play around with this or should I  test on my own?

**Comment by karolsojko** [comment]
@keremgocen I used my own for testing :)

**Comment by keremgocen** [comment]
FINE:)

**Comment by jacekelgda** [comment]
@keremgocen are you planning to implement this one ?

**Comment by keremgocen** [comment]
Yes i will, we just need to pick a centralized logging service that will aggregate lambda logs on aws cloudwatch to a central solution (ie. Loggly, splunk etc.)

**Comment by jacekelgda** [comment]
Can't we just post everything to slack channel ? For example, if you created #the-vault-activity as public channel which anyone can join if interested.

What do you think ?

**Comment by keremgocen** [comment]
We can, but i dont think slack is a good platform for log aggregation. We could however, post daily digests on a slack channel of our choice.

**Comment by jacekelgda** [comment]
This is not like heavy debug logger we are talking about ( just to clarify ). We would send up to 20 requests per day to slack channel. When someone got coin or used some of the coins etc. Slack uses web sockets as well. Just a suggestion @keremgocen , but we are going toward keeping everything in one place rather then need to log somewhere else for activity.
