### ISSUE TITLE
List by user

### ISSUE THREAD

**Issue by jacekelgda** [x-team/the-vault#24]
Admin should be able to list by user

`/listvault @username`

**Comment by keremgocen** [comment]
Is this implemented?

**Comment by jacekelgda** [comment]
`Scenario: Admin checks other users coin:`
`Given` I am "@jacek.lawniczak" user
`And` user "@jacek.lawniczak" is admin
`And` user "@kerem" has "1" coin
`And` user "@jacek.lawniczak" has "1" coin
`When` I run slash command "`/listvault @kerem`"
`Then` I should see "@kerem has 1 coin."

`Scenario: Not admin user checks other users coin:`
`Given` I am "@kerem" user
`And` user "@jacek.lawniczak" is admin
`And` user "@jacek.lawniczak" has "1" coin
`And` user "@kerem" has "1" coin
`When` I run slash command "`/listvault @jacek.lawniczak`"
`Then` I should see "You need to be admin to see other users vault."

`Scenario: Not admin user checks other user (that is him) coins:`
`Given` I am "@kerem" user
`And` user "@jacek.lawniczak" is admin
`And` user "@jacek.lawniczak" has "1" coin
`And` user "@kerem" has "1" coin
`When` I run slash command "`/listvault @kerem`"
`Then` I should see "@kerem has 1 coin."

`Scenario: Command with no params:`
`Given` I am "@kerem" user
`And` user "@jacek.lawniczak" is admin
`And` user "@jacek.lawniczak" has "1" coin
`And` user "@kerem" has "1" coin
`When` I run slash command "`/listvault`"
`Then` I should see "@kerem has 1 coin."
