### ISSUE TITLE
Spending gold coins

### ISSUE THREAD

**Issue by jacekelgda** [x-team/the-vault#3]
There should be a slash command to spend collected gold coins. The flow for this should be discussed.

**Comment by jacekelgda** [comment]
Option 1. Either admin should draw coins from user `/drawcoin {number} @user` and validation should check if user has enough coins.

Option 2. User can spend coins `/spendcoin {number}` and maybe some notification should go out to admin that `@user just spent {number} coins. Proceed with order`

Option 3. When certain number of coins is reached user can get notification: `You now are able to exchange your {number} coins for this sweet hoodie: http://x-team/shop/hoodie-1`

@ryanchartrand ^^

**Comment by keremgocen** [comment]
What's the verdict/status on this one?

**Comment by ryanchartrand** [comment]
Woops, didn't notice it was addressed to me :)

For now, it's Option 1. Eventually we'll tie the form on x-team.com/vault into automatically drawing coins and even sending out order forms using our vendor's API, but we'll put that on hold for the moment until we've done a few runs of sending out items.

**Comment by jacekelgda** [comment]
I will close this since option 1 is ready. If we find need to implement more complicated solutions I will create new issues.
