### ISSUE TITLE
Default grand and draw values

### ISSUE THREAD

**Issue by jacekelgda** [x-team/the-vault#34]
I someone runs command `/grantcoin` or `/drawcoin` without number argument it should add or subtract 1 by default.

**Comment by jedrzej** [comment]
@jacekelgda Isn't that what /grantcoin does already? I don't see it take number of coins as an argument. Only /drawcoin takes number of coins to spend as an argument.

**Comment by karolsojko** [comment]
@jedrzej it's only about `/drawcoin` 

`/grantcoin` is 1 by default already
