### ISSUE TITLE
NULL is displayed when no reason is provided

### ISSUE THREAD

**Issue by jedrzej** [x-team/the-vault#38]
It seems that if no reason for granting coins is provided, `null` string is displayed:

`You have been granted 1 new, shiny :coin: null. You now have...`

**Comment by jacekelgda** [comment]
Would you like to take this issue for development Jedrzej ? Thanks for creating :)

**Comment by jedrzej** [comment]
sure, it was assigned to me already ;)

**Comment by jacekelgda** [comment]
<img width="346" alt="screenshot 2018-03-19 15 00 34" src="https://user-images.githubusercontent.com/1003372/37599981-5b32dd9e-2b86-11e8-9409-53bf4b513b18.png">

**Comment by jacekelgda** [comment]
I run command like this: `/grantcoin @giannis.katsanos #programming-contest` but since this is a channel reference it might have a different behaviour.
