### ISSUE TITLE
Multiuser grant

### ISSUE THREAD

**Issue by jacekelgda** [x-team/the-vault#46]
When granting coins to multiple users at once the confirmation message is misleading:

<img width="835" alt="screenshot 2018-04-11 14 08 03" src="https://user-images.githubusercontent.com/1003372/38615711-ec5e79aa-3d91-11e8-8fe6-2a8f47355450.png">

I should say `... by @jake and now has ...` in all messages.

**Comment by keremgocen** [comment]
taking this
