### ISSUE TITLE
Publish current list

### ISSUE THREAD

**Issue by jacekelgda** [x-team/the-vault#5]
There is another issue for presenting the list of gold coins. 
This should ask is this list should be published in a channel or group and the publishing it there.

**Comment by keremgocen** [comment]
Do you have a channel on your mind?

**Comment by ryanchartrand** [comment]
This was implemented as /listvault which shows the whole list to admins OR just your coins if you're not an admin.

**Comment by jacekelgda** [comment]
Maybe a discussion is needed in here.
I originally created this issue to actually publish the list of coins. Somewhere in the channel there would be a public message where the list of all users with their coins would be displayed. Such list would be update each time something changed in the vault. As @ryanchartrand explained already we have `/listvault` which basically lets everyone know what is their vault balance. I think for now we can dismiss this idea unless anyone can provide valid argument for leaving this in.

**Comment by malgorzatajezierska** [comment]
I'm archiving this task.
